### ISSUE TITLE
Sqlite Migration Tracking Issue

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#1094]
See #1078 for implementation of sqlite backend & migration.

- [x] Merge sqlite backend (#1078)
- [x] Release new version of snarkOS, get users to update
- [ ] With critical mass, remove rocksdb implementation, dependency, migration script, and possibly storage validator.

**Comment by ljedrz** [comment]
@Protryon should we start removing the `rocksdb` impl now? I can do that if you're currently working on something else.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2.
